server:
  port: 8080 # The entry point for your entire system

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. User Service (Authentication)
        - id: digi-wallet-user-service
          uri: http://localhost:8081 # Direct URL
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**, /api/v1/admin/**

        # 2. notification
        - id: digi-wallet-notification-service
          uri: http://localhost:8082 # Direct URL
          predicates:
            - Path=/api/v1/notification/**
#          filters:
#            - name: RequestRateLimiter # Example: Prevent spamming
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                key-resolver: "#{@userKeyResolver}" # Must match the bean name above

        # 3. wallet-Service
        - id: digi-wallet-service
          uri: http://localhost:8083 # Direct URL
          predicates:
            - Path=/api/v1/wallet/**

#        # 4. transaction Service
        - id: digi-wallet-transaction-service
          uri: http://localhost:8084 # Direct URL
          predicates:
            - Path=/api/v1/transaction/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"  # front end port
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: ${JWT_SECRET_KEY}